name: Create and publish an Alpine Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file Dockerfile.alpine \
            --label org.opencontainers.image.created=$(date --utc +%Y-%m-%dT%H:%M:%SZ) \
            --label org.opencontainers.image.description="PS3DEC Alpine-based Docker image" \
            --label org.opencontainers.image.licenses=MIT \
            --label org.opencontainers.image.revision=${{ github.sha }} \
            --label org.opencontainers.image.source=https://github.com/${{ github.repository }} \
            --label org.opencontainers.image.title=ps3dec-docker \
            --label org.opencontainers.image.url=https://github.com/${{ github.repository }} \
            --label org.opencontainers.image.version=${{ github.ref_name }} \
            --tag ghcr.io/sthopeless/ps3dec-docker:alpine \
            --push .
